version: "3.3"
services:
  client:
    image: saykot/blog-frontend:1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - web
      - mongo
  web:
    image: saykot/blog-backend:1.0.0
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - EMAIL=<email>
      - EMAIL_PASSWORD=<emailpassword>
      - TOKENSECRATE=lksdajlkjslkajklklsfakklsajkljakljflkjjlkajkljfjflklkksakfjdsafljkajskslsa
      - DATABASE_URL=mongodb://mongo:27017/blogapp
      - CLIENT_URL=http://localhost:3000
    volumes:
      - photos:/usr/src/app/server/upload
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017"
    volumes:
      - data:/data/db
volumes:
  data:
    driver: local
  photos:
    driver: local
