version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - web
      - mongo

  web:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - EMAIL=appDiployerEmail
      - EMAIL_PASSWORD=appDiployerEmailPassword
      - TOKENSECRATE=lksdajlkjslkajklklsfakklsajkljakljflkjjlkajkljfjflklkksakfjdsafljkajskslsa
      - DATABASE_URL=mongodb://mongo:27017/blogapp
      - CLIENT_URL=http://localhost:3000
    volumes:
      - photos:/usr/src/app/server/upload
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-express-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

volumes:
  mongo-express-data:
    driver: local
  photos:
    driver: local
